const E=require('./engine.js'); const D=require('./data_spring_msi.json'); const P=E.prepGames(D);
const U=P.champs, nU=U.length;
const train=P.games.filter(g=>g.lg!==6), test=P.games.filter(g=>g.lg===6);
const ptRanks=[...new Set(P.games.map(g=>g.ptr))];
const top=E.topByPatchFor(train,U,20,ptRanks);
const W=o=>E.gameWeights(train,U,{half:21,pmult:1.5,...o},top);
const st=E.rawStats(train,U), n=train.length, M={};
M['Presence (P+B ÷ games)']=new Map(U.map(c=>[c,(st.get(c).p+st.get(c).b)/n]));
M['gol.gg-style PrioScore']=new Map(U.map(c=>[c,st.get(c).gol/n]));
M['Base (availability-adjusted)']=E.score(train,U,{});
M['Base + series depth']=E.score(train,U,{},W({depth:true}));
M['Base + shrink']=E.score(train,U,{shrink:true,k:10});
M['Base + per-team']=E.score(train,U,{team:true});
M['Base + recency']=E.score(train,U,{},W({recency:true}));
M['Base + deciding games']=E.score(train,U,{},W({pressure:true}));
M['Mix (all five add-ons)']=E.score(train,U,{shrink:true,k:10,team:true},W({depth:true,recency:true,pressure:true}));
M['Recommended mix (recency + deciding + shrink)']=E.score(train,U,{shrink:true,k:10},W({recency:true,pressure:true}));
M['Base + recency, half-life 10 days']=E.score(train,U,{},W({recency:true,half:10}));
M['Base + recency, half-life 42 days']=E.score(train,U,{},W({recency:true,half:42}));
const ch=E.buildChoices(train,U); const md=Math.max(...train.map(g=>g.day));
const PLm=(wf,label,chs=ch)=>{const g=E.fitPL(chs,nU,wf,1,80); M[label]=new Map(U.map((c,i)=>[c,g[i]])); return g;};
PLm(null,'Plackett–Luce'); PLm(g=>Math.pow(0.5,(md-g.day)/21),'Plackett–Luce + recency');
const gamX=PLm(g=>Math.pow(0.5,(md-g.day)/10)*(g.pressure?1.5:1),'xPresence as published (10-day half-life, deciding 1.5×)');
const tS=train.filter(g=>g.lg<=1), mdS=Math.max(...tS.map(g=>g.day));
PLm(g=>Math.pow(0.5,(mdS-g.day)/10)*(g.pressure?1.5:1),'xPresence from LCK + LPL only',E.buildChoices(tS,U));
const isPL=nm=>nm.startsWith('Plackett')||nm.startsWith('xPresence');
const feat=(m,pl)=>Float64Array.from(U,c=>pl?Math.log(m.get(c)):Math.log((m.get(c)||0)+0.01));
const llA=(chs,x,b)=>chs.map(c=>{let mx=-1e9;for(const j of c.S)mx=Math.max(mx,b*x[j]);let z=0;for(const j of c.S)z+=Math.exp(b*x[j]-mx);return b*x[c.c]-mx-Math.log(z);});
const mean=a=>a.reduce((s,v)=>s+v,0)/a.length;
const fitBeta=(chs,x)=>{let lo=0,hi=4;for(let i=0;i<28;i++){const m1=lo+(hi-lo)/3,m2=hi-(hi-lo)/3;if(mean(llA(chs,x,m1))<mean(llA(chs,x,m2)))lo=m1;else hi=m2;}return (lo+hi)/2;};
const chT=E.buildChoices(test,U); const uni=mean(llA(chT,new Float64Array(nU),0));
const tb=E.score(test,U,{}); const seen=U.filter(c=>test.some(g=>g.acts.some(a=>a.c===c)));
const rk=a=>{const o=a.map((v,i)=>[v,i]).sort((p,q)=>q[0]-p[0]);const r=new Array(a.length);o.forEach(([,i],k)=>r[i]=k);return r;};
const sp=(a,b)=>{const ra=rk(a),rb=rk(b),N=a.length;let d=0;for(let i=0;i<N;i++)d+=(ra[i]-rb[i])**2;return 1-6*d/(N*(N*N-1));};
const per={}, rows=[];
for(const [name,m] of Object.entries(M)){const x=feat(m,isPL(name)),b=fitBeta(ch,x),v=llA(chT,x,b);per[name]=v;rows.push({name,ll:mean(v),gain:mean(v)-uni,beta:b,rho:sp(seen.map(c=>m.get(c)),seen.map(c=>tb.get(c)))});}
const sids=[...new Set(chT.map(c=>c.g.sid))]; const bySid=nm=>{const mp=new Map();chT.forEach((c,i)=>{const o=mp.get(c.g.sid)||{s:0,n:0};o.s+=per[nm][i];o.n++;mp.set(c.g.sid,o);});return mp;};
const G=bySid('gol.gg-style PrioScore'), gol=rows.find(r=>r.name==='gol.gg-style PrioScore');
let seed=42;const rnd=()=>{seed=(seed*1103515245+12345)&0x7fffffff;return seed/0x80000000;};
const draws=[...Array(2000)].map(()=>sids.map(()=>sids[Math.floor(rnd()*sids.length)]));
const out=rows.map(r=>{const S=bySid(r.name);const d=draws.map(dr=>{let a=0,n=0;dr.forEach(k=>{a+=S.get(k).s-G.get(k).s;n+=S.get(k).n;});return Math.exp(a/n)-1;}).sort((x,y)=>x-y);
  return {name:r.name,vsGol:+(Math.exp(r.ll-gol.ll)-1).toFixed(4),lo:+d[100].toFixed(4),hi:+d[1899].toFixed(4),gain:+r.gain.toFixed(4),ll:+r.ll.toFixed(5),rho:+r.rho.toFixed(3),beta:+r.beta.toFixed(2)};}).sort((a,b)=>b.vsGol-a.vsGol);
// predicted vs actual top 10
const take=E.plTakeRate(gamX); const stT=E.rawStats(test,U); const pres=U.map(c=>(stT.get(c).p+stT.get(c).b)/test.length);
const rX=new Map(U.map((c,i)=>[c,i]).sort((a,b)=>take[b[1]]-take[a[1]]).map(([c],k)=>[c,k+1])), rM=new Map(U.map((c,i)=>[c,i]).sort((a,b)=>pres[b[1]]-pres[a[1]]).map(([c],k)=>[c,k+1]));
const nm=c=>D.C[c]; const iU=new Map(U.map((c,i)=>[c,i]));
const predTop=[...U].sort((a,b)=>take[iU.get(b)]-take[iU.get(a)]).slice(0,10).map(c=>({n:nm(c),x:+take[iU.get(c)].toFixed(3),msi:+pres[iU.get(c)].toFixed(3),msiRank:rM.get(c)}));
const actualTop=[...U].sort((a,b)=>pres[iU.get(b)]-pres[iU.get(a)]).slice(0,10).map(c=>({n:nm(c),msi:+pres[iU.get(c)].toFixed(3),x:+take[iU.get(c)].toFixed(3),xRank:rX.get(c)}));
const res={train:train.length,test:test.length,actions:chT.length,uniform:+uni.toFixed(5),series:sids.length,rows:out,pred:{predTop,actualTop,hitTop10:predTop.filter(r=>r.msiRank<=10).length}};
require('fs').writeFileSync('msi3.json',JSON.stringify(res));
console.log(res.train,res.test,res.actions,res.series); out.forEach(r=>console.log(r.name.padEnd(58),(r.vsGol*100).toFixed(1),(r.lo*100).toFixed(1),(r.hi*100).toFixed(1),r.rho));
console.log('top10 hit',res.pred.hitTop10, predTop.map(r=>r.n+'#'+r.msiRank).join(', ')); console.log(actualTop.map(r=>r.n+'#'+r.xRank).join(', '));
